### ISSUE TITLE
Why must we allow elevated privileges for `dotnet workload restore`?

### ISSUE THREAD

**Issue by daveyostcom** [AngelMunoz/NXUIFSharpMultiPlatformTemplate#1]
Please update the README.md to explain this and to say why not to worry.

On macOS:
```
Z% dotnet workload restore
Installing workloads: wasm-tools-net7 ios
Inadequate permissions. Run the command with elevated privileges.
Z%
```

**Comment by AngelMunoz** [comment]
This is related to the dotnet workloads you can find why elevation is needed here:

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install#when-to-run-elevated

I will add it, thanks to point it out
